### PR TITLE
Display prefecture after Dojo name (instead of region name)

### LINKED ISSUE #380: 道場の表示方法を「Dojo 名（県名）」に変更する
## 背景

image
cf. https://www.facebook.com/groups/coderdojo.jp/permalink/2018854421561280/

## 変更案

image
cf. https://www.facebook.com/groups/coderdojo.jp/permalink/2018854421561280/?comment_id=2019695501477172&comment_tracking=%7B%22tn%22%3A%22R%22%7D

### PR DESCRIPTION
**Pull request by yasulab**
Fix #380 

This PR changes the following 2 things:

## 1. Display prefecture name instead of region name:
- Delete hard-coded region name in `/db/dojos.yaml`
- Display prefecture name after Dojo name

image

## 2. Records in DB:
- Change records in Prefecture model like this:
   - 北海道 -> 北海道
   - 東京都 -> 東京
   - 大阪府 -> 大阪
   - 沖縄県 -> 沖縄

### CODE REVIEW

**Comment by yasulab** [comment]
Will merge this PR when CI passes ✅ 👀

**Comment by yasulab** [comment]
Locally checked that this works fine. ✅ ✨

**Comment by nalabjp** [comment]
@yasulab 
Sorry for replying so late.
Why do we need this commit ac0215c ?
It seems unnecessary for the purpose of this PR.

**Comment by yasulab** [comment]
> It seems unnecessary for the purpose of this PR.

@nalabjp Yeah, I thought this not necessary, but through creating this PR I needed to update some of dojo names as noted at `## 2. Records in DB`. And I found this changed the order of dojo listing. So I put this code to set order by ascending.

But what I care about is the order and result, so if the order and result is same as now, I'm not against to deleting this code. ;)

**Comment by nalabjp** [comment]
@yasulab 
Thank you for your easy explanation.
I believe that orders in prefectures are already collateralized.
That's because `Dojo.default_order` scope is applied to the return value of the following code.

https://github.com/coderdojo-japan/coderdojo.jp/blob/ae8da6c57f5bfe70c5ef10513357929f472816ba/app/controllers/home_controller.rb#L4
https://github.com/coderdojo-japan/coderdojo.jp/blob/ae8da6c57f5bfe70c5ef10513357929f472816ba/app/models/dojo.rb#L13

**Comment by yasulab** [comment]
@nalabjp Thanks for explaining code by code. 🆒✨ I have deleted the line in this commit. ;) https://github.com/coderdojo-japan/coderdojo.jp/commit/ff6a548625743bc715d9444e9ba57f45f416bc74

**Pull request merged**
